### ISSUE TITLE
OVAL Results Readability and Traceability 

### ISSUE THREAD

**Issue by djhaynes** [scapcommunity/XCCDF#11] opened 2019-11-25 13:41 UTC
**Challenge:** Depending on what is being checked, OVAL results can be very large documents that are difficult to comprehend due to the relational nature of OVAL and burdensome to communicate between systems due to their size. Furthermore, it is difficult to determine the root cause of check failures in an automated way.

**Proposal:** Examine the OVAL results schema and look for opportunities to improve the human-readability of results, better track the parameterization of checks, and identify the root cause of check failures.

**Comment by djhaynes** [comment] 2019-11-26 13:03
Previous discussions on OVAL Results.

https://oval.mitre.org/community/docs/OVAL-Dev-Days-06-14-2010.pdf
https://oval.mitre.org/community/docs/OVAL_Developer_Days_2010_Minutes.pdf

Also, look at OVAL Results Directives and the applicability_check attribute in OVAL Definitions.

**Comment by DavidRies** [comment] 2019-12-03 18:22
I think this should be split into 3 separate issues:

- Making results format smaller, more readable (moved to #19 and backlogged)
- Tracking parameterization of checks through to results (moved to #20 and backlogged)
- Enabling easier identification of root causes of results

**Comment by DavidRies** [comment] 2019-12-19 16:01
I am interested in working the "enabling easier identification of root causes of results" portion of this issue. Does anyone have ideas/interest in tracking parameterization through to results or make results format smaller and more readable? If so, I will put those in another ticket.

**Comment by djhaynes** [comment] 2019-12-19 18:48
**ACTION:** Bill will see if he can share work in this area for backlogged items they currently have. No promises here.

**Comment by djhaynes** [comment] 2020-02-20 15:44
@wmunyan did you get a chance to see if you can share work related to this issue?

**Comment by wmunyan** [comment] 2020-02-20 16:25
Internal discussions are in-progress on sharing code/library/api.  We are hacking on some of this code during the week after the workshop, as well.

**Comment by DavidRies** [comment] 2020-08-19 17:26
Our working document addressing OVAL Applicability is also intended to address the "enabling easier identification of root causes of results" component of this issue.

See: https://github.com/scapcommunity/XCCDF/blob/master/working-documents/oval-applicability-problem-statement-ideas.md

**Comment by DavidRies** [comment] 2020-09-25 13:52
As per phone conference, this work on enabling easier identification of root causes of results will be handling as a part of #15. Closing this Issue.

**Closed as completed by DavidRies** 2020-09-25 13:52 UTC
Labels: enhancement, OVAL, LOE: medium
